fav_fruit = ["apple","banana","grape","green mango","strawberry"]
print(fav_fruit)

print("Length of list: ", len(fav_fruit))
print("Type of fruit", type(fav_fruit))
fav_fruit.append("blueberry")
print(fav_fruit)
fav_fruit.insert(1,"blueberry")
print(fav_fruit)
fav_fruit.remove("banana")
print(fav_fruit)
fav_fruit.pop(3)
print(fav_fruit)
fav_fruit.reverse()
print(fav_fruit)
fav_fruit.sort()
print(fav_fruit)
fav_fruit.clear()
print(fav_fruit)